### ISSUE TITLE
Discrepancy between sanitisation of Java and JavaScript templates (autoescaping of let value)

### ISSUE THREAD

**Issue by thomas-schwebel** [google/closure-templates#105]
Hi,

I am using a compiled Soy template to Javascript and I am running into an escaping issue. 
Printing an intermediate value built with `let` and a kind of "html" escapes its content.
I am not sure if this is an issue or I am maybe just missing the correct way to do it.

The same approach works on the server side (with Java) but not when compiled to Javascript. This discrepancy for such a trivial use case makes me believe that other people have or might fall into this issue.

Here is a simple example that I compile:
```
/**
*/
{template .foo}
    {let $bar kind="html"}
        {call .bar/}
    {/let}

    {call .bar/}
    -------------------
    {$bar}
{/template}

/**
*/
{template .bar}
    <b>BAR</b>
{/template}
```

The javascript code that I get from this is:
```
pubse.includes.adBlock.foo = function(opt_data, opt_ignored, opt_ijData) {
  var output = '';
  var bar__soy308 = '' + pubse.includes.adBlock.bar(null, null, opt_ijData);
  bar__soy308 = soydata.VERY_UNSAFE.$$ordainSanitizedHtmlForInternalBlocks(bar__soy308);
  output += pubse.includes.adBlock.bar(null, null, opt_ijData) + '-------------------' + soy.$$escapeHtml(bar__soy308);
  return soydata.VERY_UNSAFE.ordainSanitizedHtml(output);
};
if (goog.DEBUG) {
  pubse.includes.adBlock.foo.soyTemplateName = 'pubse.includes.adBlock.foo';
}


pubse.includes.adBlock.bar = function(opt_data, opt_ignored, opt_ijData) {
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<b>BAR</b>');
};
if (goog.DEBUG) {
  pubse.includes.adBlock.bar.soyTemplateName = 'pubse.includes.adBlock.bar';
}
```

The result from calling this function is:
```
b {content: "<b>BAR</b>-------------------&lt;b&gt;BAR&lt;/b&gt;"}
```

As you can see:
- calling the template directly respects the kind "html" (default for template) and doesn't escape it
- calling the template into the `foo` variable using `let` respects the specified kind "html" but as soon as it is printed with `{$bar}` it is escaped (`soy.$$escapeHtml(bar__soy308)` in JavaScript).

My problem is that I don't want the latter to be escaped. I thought that specifying the `let` kind to "html" would help but it does not.
Am I doing something wrong? Is there a way to accomplish this?

This is how I compile the templates:
I am using the latest `SoyToJsSrcCompiler` that I compiled myself with the latest from github.com/google/closure-templates: `soy-2016-01-12-SoyToJsSrcCompiler`.
Using this executable jar I then compile the Soy files to Javascript.

Thanks in advance,
Thomas

**Comment by matiwinnetou** [comment]
+1, this is confusing

**Comment by matiwinnetou** [comment]
Perhaps this is bug or a proper "gotcha".

**Comment by matiwinnetou** [comment]
Could somebody help to find out what is going wrong?

**Comment by lukesandberg** [comment]
with autoescape="strict" this isn't reproducible at head. (are you using a different escaping mode?)

In theory the call to soy.$$escapeHtml(bar_soy308) should be a no-op since bar__soy308 was sanitized just above, this is what happens when i try to debug through these functions.  

I also tried syncing back to the 2016-01-12 release and also was unable to reproduce the issue.  My current theory is that something is wrong with the version of soy_utils.js you are using such that the short circuiting logic in escapeHtml isn't triggering

**Comment by thomas-schwebel** [comment]
Thanks for the reply @lukesandberg.
I've debugged again our code and I finally found the issue. It was on our side, we exported the wrong symbol for `soydata.VERY_UNSAFE.$$ordainSanitizedHtmlForInternalBlocks` which was always returning unsanitizedText.
Apologies.
