### ISSUE TITLE
SoyToIncrementalDomSrcCompiler issue on Windows

### ISSUE THREAD

**Issue by mairatma** [google/closure-templates#111]
The most recent version of the compiler available in [maven](http://repo1.maven.org/maven2/com/google/template/soy/2016-08-25/soy-2016-08-25-SoyToIncrementalDomSrcCompiler.jar) is currently throwing errors when building soy files that were edited in Windows. 

For example, take this simple soy file created on a Windows machine:

```
{namespace Modal}

/**
 *
 */
{template .render}
  <div>Hello World</div>
{/template}
```

It triggers the following error:

```
errors during Soy compilation
In file src/Modal.soy:1:18: parse error at '
': expected eof, {alias, {deltemplate, or {template
{namespace Modal}
```

**Comment by sparhami** [comment]
The error message seems to come from the parsing pass before the Incremental DOM code generation. Could you confirm whether or not this happens when trying to compile the same file to Java or JavaScript?

**Comment by mairatma** [comment]
Yes, same thing happens when using SoyToJsSrcCompiler instead.

**Comment by mairatma** [comment]
@sparhami do you have an idea of when a fix for Windows could be released (either on maven or npm)? We have some developers on Windows which are being blocked by this :(

**Comment by sparhami** [comment]
Could you upload an example file that exhibits the problem somewhere?

**Comment by mairatma** [comment]
Sure, here it is: [Modal.soy.zip](https://github.com/google/closure-templates/files/534230/Modal.soy.zip)

**Comment by sparhami** [comment]
Looks like adding the windows newline to the list of skipped characters here works for that error. That is, add `| "\r\n"` to

https://github.com/google/closure-templates/blob/8c383d18fd8bfc3a4e68167ff96821011940638a/java/src/com/google/template/soy/soyparse/SoyFileParser.jj#L537

But this brings up another error:

> Modal.soy:3:1: error: parse error at '/**
> ': expected eof, {alias, {deltemplate, or {template
> /**
> ^

Looking at a hexdump of the file, it looks like the `/**` is actually "2f0a 2a2a" or `/` followed by a line feed, followed by `**`. I think this confuses the part of the parser that would be looking for a comment start. The parser doesn't completely strip whitespace, it just ignores it as it goes. So what looks like the start of a comment there does not actually match what it would consider the start of a comment.

I'm not sure what to do about this one.

**Comment by mairatma** [comment]
Just so you know, it seems like this used to work with the compiler available in [npm](https://www.npmjs.com/package/closure-templates-incrementaldom). At least windows users were using it without any problems back then.

**Comment by damishaziz** [comment]
i am facing the same issue on Windows. You have to just modify your soy file like this...

{namespace Modal}/****/{template .render}
  <div>Hello World</div>
{/template} 

i mean remove the Enter key.

**Comment by lukesandberg** [comment]
Looks like this breakage was introduced by https://github.com/google/closure-templates/commit/e1a9d36a371c303b316ff3d9df22ec547b81c4ba due to what appears to have been an accidental change in our grammar.

A fix should be available soon.

**Comment by tipsy** [comment]
@lukesandberg any update on this?

**Comment by prasannasv** [comment]
@lukesandberg any ETA on this?
