### ISSUE TITLE
SoyToIncrementalDomSrcCompiler doesn't allow using variable to define attribute name

### ISSUE THREAD

**Issue by mairatma** [google/closure-templates#112]
Take the following template:

```
/**
 * @param key
 * @param value
 */
{template .fieldAttr kind="attributes"}
    {$key}="{$value}"
{/template}
```

This causes the compiler to throw an error like this:

```
For Incremental DOM, {print} statements in attributes context can only be of kind attributes (since they must compile to semantic attribute declarations).  UNKNOWN is not allowed.
        {$key}="{$value}"
        ^
```

I've noticed that it allows the right side of the assignment to be a variable, but not the left one. For example, this wouldn't throw an error, since the attribute name is not a variable anymore:

```
/**
 * @param value
 */
{template .fieldAttr kind="attributes"}
    key="{$value}"
{/template}
```

I understand that the compiler needs the format to be very specific so it can transform it into `iattr` calls, but I think it should be possible to extract this simple case to something like:

``` js
iattr(opt_data.key, opt_data.value)
```

**Comment by sparhami** [comment]
Just to note, this restriction also exists for tag names.

One problem with allowing a variable as the attribute value is it is hard to tell if, for example, the variable name might end up being something like onclick. You would not want to use with a user supplied value. If the attribute name is the result of an arbitrary expression, you can't really determine what it is.

I believe if you use the strict autoescaping mode with regular JS template compilation, the same restriction should apply.

Is there a particular use case you are thinking of where you need this functionality?

**Comment by mairatma** [comment]
@sparhami yeah, we're currently using soy templates with incremental dom in a library we've created for building components. We'd like to allow developers to specify html attributes that they want to add to a component's element, without having to create a specific option to each possible attribute that they may wish. So basically, the idea is receiving an object from attribute names to their values, and using that in soy to build the appropriate `iattr` call.

`iattr` supports passing a variable, so it seems like it would be doable to just detect and pass it instead of only allowing raw strings. Maybe that didn't make sense for the previous js compilation, since it had to build and add the html string itself but, since this is using incremental dom now, even if the value isn't a valid attribute name this would be handled by the incremental dom library, soy shouldn't have to worry about that.  Without this soy templates become very limited for attribute usage, it requires covering any possible usage of the developer with new new params, instead of allowing a flexible way to add new attributes, which incremental dom supports.

**Comment by sparhami** [comment]
> We'd like to allow developers to specify html attributes that they want to add to a component's element, without having to create a specific option to each possible attribute that they may wish.

Typically the way we have structured this in soy templates is to do something like:

```
{template .component}
  {@param? attributes: attributes}
  
  <div attr="value" {if $attributes}{$attributes}{/if}>
    ...
  </div>
{/template .component}
```

Which would then be used as follows:

```
{template .foo}
  {call .component}
    {param attributes kind="attributes"}
      data-my-attr="value"
    {/param}
  {/call}
{template}
```

This allows the attributes logic to live entirely in the templates rather than being split up between JS and the templates. Does this pattern work for your use case?

**Comment by mairatma** [comment]
Is there a way to convert a javascript object or something like that so it can be passed as an `attributes` type? The call site wouldn't be another soy template, just javascript, passing some data down to this component.

**Comment by sparhami** [comment]
Could you expand a bit on what kind of attributes would be added here? It isn't quite clear how the use case exactly goes, but I would recommend keeping the attributes logic in Soy itself if you can. Another option might be for the call site to pass a Soy template that contains the attributes they want in it. Something like:

```
{template kind="attributes"}
  data-my-attr="value"
{/template}
```

And if they need some data to render those, they could either bind it in, or pass the data for you to pass to the template.

If you really want to allow them to pass an `Object`, you could do something like:

```
{template .foo}
  {@param attributes: attributes}
{/template}
```

```js
function renderFoo(attributes) {
  var attributesFn = function() {
    for (var name in attributes) {
      IncrementalDOM.attr(name, attributes[name]);
    }
  };
  patch(el, templateFn, {
    attributes: attributesFn
  });
}
```

Note that this relies on the code generation using the `attr` function. This will be changing in the near future to use the [new API outline here.](https://github.com/google/incremental-dom/issues/254).

Another approach might be to use a [SoyFunction](https://github.com/google/closure-templates/blob/8c383d18fd8bfc3a4e68167ff96821011940638a/java/src/com/google/template/soy/shared/restricted/SoyFunction.java), though this is currently not supported by the incremental DOM code generation in an attributes declaration. This could possibly look like the following:

```
  {template .foo}
    {@param attributes: attributes}
    <div {renderAttributes($attributes)}></div>
  {/template}
```

The SoyFunction would then need to emit the calls to the `attr` function.

**Comment by mairatma** [comment]
Unfortunately we can't pass it down via soy, our library is template agnostic, so the call site for a soy component doesn't need to be using soy too. When a soy component is exported people don't even need to know it used soy, they can call it passing params directly from javascript.

Converting the object to `IncrementalDOM` calls is a good idea, but it would only work on javascript side, and we need the templates to be able to render in java as well. Btw, do you know if the java compiler allows using variables when defining attributes, like in my example?

`SoyFunction` seems promising, but can you explain to me a bit more how it'd work? Where would I tie the implementation of the defined function (both in js and in java)? Is there some step by step guide?

Thanks a lot for helping out!

**Comment by sparhami** [comment]
> Converting the object to IncrementalDOM calls is a good idea, but it would only work on javascript side, and we need the templates to be able to render in java as well. Btw, do you know if the java compiler allows using variables when defining attributes, like in my example?

Now that you mention it, it seems like it is supported for Java code generation so I don't think there is any reason not to support it for Incremental DOM code generation.

**Comment by sparhami** [comment]
Looks like adding the windows newline to the list of skipped characters here works for that error. That is, add `|  "\r\n"` to

https://github.com/google/closure-templates/blob/8c383d18fd8bfc3a4e68167ff96821011940638a/java/src/com/google/template/soy/soyparse/SoyFileParser.jj#L537

But this brings up another error:

> Modal.soy:3:1: error: parse error at '/**
> ': expected eof, {alias, {deltemplate, or {template
> /**
> ^
> 

Looking at a hexdump of the file, it looks like the `/**` is actually "2f0a 2a2a" or `/` followed by a line feed, followed by `**`. I think this confuses the part of the parser that would be looking for a comment start. The parser doesn't completely strip whitespace, it just ignores it as it goes. So what looks like the start of a comment there does not actually match what it would consider the start of a comment.

I'm not sure what to do about this one.

**Comment by brunobasto** [comment]
Hey @sparhami, since this issue was created I noticed there is a new release out: https://github.com/google/closure-templates/tree/release-2017-02-01

Do you know if with this new version the IncDOM compiler will allow using variables for defining attribute names?

/cc @fernandosouza

**Comment by sparhami** [comment]
I know that there is some work going on inside closure-templates to make the compilation to Incremental DOM more similar to the rest of the code base, which should enable it to do all the things regular closure-templates does, including variables for attribute names.

I don't know the current status, but @lukesandberg might have more info.

**Comment by matuzalemsteles** [comment]
Any updates on that?

**Comment by lukesandberg** [comment]
We do plan on fixing this particular issue as part of our current efforts on incremental dom.  i suspect that this will be resolved in the next few months

**Comment by iteriani** [comment]
A little bit late, but this works now.
