### ISSUE TITLE
Question about parameters

### ISSUE THREAD

**Issue by rlambert27** [google/closure-templates#113]
Hello,

I don't have an issue really, I have a question. We compile our SOY files and in our web pages we have sections that relate to 5 different templates in our compiled JS file. One of the parameters is common to all 5 templates but our developers need to declare this parameter in each call to the compiled JS file.

Is there an easier way of doing this? Like a global option that would be set once in the first call to the compiled JS file and then reused for the other 4 templates?

Roch

**Comment by hochhaus** [comment]
Yes, closure templates support globals. In JS you can bind them at compile or render time.

https://developers.google.com/closure/templates/docs/javascript_usage#globals

Be careful using render time globals though as doing so creates a tight dependency your templates and runtime.

```
Any global that is not bound at compile time appears in the generated
code as a JavaScript name, which is resolved at render time. You must
ensure that any such global names are in fact defined in the JavaScript
environment at render time.

Note: Avoid using render-time globals unless absolutely necessary,
because it makes for tight coupling between your template and your
runtime environment.
```

**Comment by rlambert27** [comment]
Would you have a simple example of this? I'm trying to wrap my head around where I would declare this global variable? I'm using the SoyToJsSrcCompiler file but i'm unsure where to add the global variable?

I don't see an example of this in the sample code files.

**Comment by rlambert27** [comment]
Would anybody have an example of this?

**Comment by lukesandberg** [comment]
globals are good for constants.  you can reference them from soy like

{template .foo}
  {if some.global.reference}hello{/if}
{/template}

and then pass them to the compiler by writing the definitions into a 'properties' file that looks like

some.global.reference=false

and passing it to the compiler via the --compileTimeGlobals flag.  If you don't pass the flag (and are only generating javascript sources), then we will just output code that references 'some.global.reference' so if it is defined in your JS environment it will still work.

you might also be interested in using the `$ij` param support.
https://developers.google.com/closure/templates/docs/concepts#injecteddata
