### ISSUE TITLE
Parameters in lowercase

### ISSUE THREAD

**Issue by rlambert27** [google/closure-templates#116]
Hello,

Is their a function to set the parameters to lowercase? Some developers are not putting their parameters in lowercase so when we loop through our IF functions in the SOY file a parameter from the developer like "envQAT" doesn't match what we have in our SOY which would be "envqat". 

Is their a way to take the parameter from the developer and force it to lowercase?

I check the soyutils file but coudln't find anything.

Thanks!

**Comment by lukesandberg** [comment]
there is no such utility.

if you use closure compiler (and pass --shouldGenerateJsDoc) you should be able to get type checking from the compiler.  Otherwise i suggest using unit tests :/
