### ISSUE TITLE
How to iterate over protobuf repeated field?

### ISSUE THREAD

**Issue by pcj** [google/closure-templates#117]
Trying out the new protobuf support!  I was expecting this to work:

```protobuf
syntax = "proto3"

package my;

message TestMessage {
  repeated FooBar foobars = 1;
}

message FooBar {
  string baz = 1;
}
```

```html
{template .test}
 {@param m: my.TestMessage}
 {foreach $foobar in $m.foobars}
  <div>{$foobar.baz}</div>
 {/foreach}
{/template}
```

What am I doing wrong? Is it possible to iterate over repeated fields?

**Comment by lukesandberg** [comment]
The accessor is named foobarsList. Try that

**Comment by pcj** [comment]
Wow fastest response ever.  It works, thank you!

![](http://i.giphy.com/jErnybNlfE1lm.gif)

**Comment by lukesandberg** [comment]
:)

In the google3 internal fork for closure-templates we actually have a
suggestion for this error (e.g. Did you mean .foobarsList?), but it relies
on a google internal edit distance library.. there was an effort to open
source that library (which would make it easy for us to opensource our typo
suggestions).  I'll follow up on that.
