### ISSUE TITLE
Template commands nested in {literal} ... {/literal} are still parsed.

### ISSUE THREAD

**Issue by Robert-Frampton** [google/closure-templates#120]
According to [Closure documentation](https://developers.google.com/closure/templates/docs/commands#literal) all text within `{literal}` blocks should not be parsed, including template commands.

```
{namespace test}

/**
 *
 */
{template .render}
	<div>
		{literal}
			{template .snippet}
				<span>Code snippet.</span>
			{/template}
		{/literal}
	</div>
{/template}
```

When attempting to render this template, the following error is thrown.

```
soynode: Compile error
 In file test.soy, template test.render: Lexical error at line 12, column 25.  Encountered: <EOF> after : ""
In file test.soy:12:17: parse error at '{': expected eof, {deltemplate, or {template
		{/literal}
                ^

soynode: Error: Error compiling templates
    at ChildProcess.onExit (/Projects/temp/node_modules/soynode/lib/SoyCompiler.js:308:25)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
soynode: emit error Error: Error compiling templates
    at ChildProcess.onExit (/Projects/temp/node_modules/soynode/lib/SoyCompiler.js:308:25)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

A similar error is thrown if `{namespace ns}` is included inside the `{literal}` tags.

**Comment by lukesandberg** [comment]
I cannot reproduce this at head.  and based on the fact that the error displays a 'Lexical error' (which im pretty sure i completely eliminated about a year ago), im guessing you are on an older version of soy.

can you see if this still reproduces with a more up to date version

**Comment by eduardolundgren** [comment]
@Robert-Frampton Are you using soy to incremental dom compiler?

**Comment by Robert-Frampton** [comment]
I'm testing with a very simple test case with [soynode](https://www.npmjs.com/package/soynode), which implements the latest version of the [closure-templates](https://www.npmjs.com/package/closure-templates) npm package. 

However it looks like this package hasn't been published for some time, which is probably why I ran into this issue.

**Comment by mairatma** [comment]
Yes, I think that even though there's a new version of the soy compiler, this **closure-templates** npm package doesn't have it yet. The version in [maven](http://repo1.maven.org/maven2/com/google/template/soy/2016-08-25/) is from August of this year while closure-templates is still on 2015, unfortunately. Updating it would probably work.
