### ISSUE TITLE
Usage example for SoyToJbcSrcCompiler

### ISSUE THREAD

**Issue by brunobasto** [google/closure-templates#124]
Is there an usage example for the `SoyToJbcSrcCompiler`? Something on the lines of the `SoyToPySrcCompiler` or `SoyToJsSrcCompiler` would be nice.

Also, I don't see a jar for this specific compiler. I'm just running `mvn` at the root of the project. Is there anything else I need to do?

Thank you!

**Comment by lukesandberg** [comment]
yeah sorry.  while this is being used at google, open source examples/artifacts have not been produced as of yet.  I'm not sure when we will get around to this, but ill assign it to myself so i don't easily forget

**Comment by brunobasto** [comment]
That would be awesome. Thanks again.

**Comment by iteriani** [comment]
I _think_ this has been released (afaik)
