### ISSUE TITLE
Kickstart this project properly!

### ISSUE THREAD

**Issue by igorspasic** [google/closure-templates#14]
We do not understand why Google is not putting more energy into this project? It was cool, but soon it staled, without any improvements in years!

Please, kickstart this project properly:

+ close old Google code project and put a link to this repo;
+ update official page with new repo link;
+ migrate issues (that make sense) from old repo to this new repo;
+ add README etc.
+ explain the status of this project and future plans.
+ add Maven artifacts
+ think on migrating to gradle

Thank you.

**Comment by Ubehebe** [comment]
We're now able to accept outside contributions for the source code ([directions](https://github.com/google/closure-templates/blob/master/CONTRIBUTING.md)). (We're also working on putting the official documentation here, so outside contributors can improve those, too.) PRs welcome!

**Comment by lfac-pt** [comment]
Awesome! Thanks :)

**Comment by igorspasic** [comment]
:+1:

**Comment by Ubehebe** [comment]
I'm going to close this issue now. If you have more specific concerns, feel free to open more specific issues.
