### ISSUE TITLE
Can't run Soy compiler via API without System.exit

### ISSUE THREAD

**Issue by tntim96** [google/closure-templates#142]
We used to be able to run `SoyToJsSrcCompiler.main(...)` to compile multiple source directories with different options, however, recent changes call `System.exit(status);`, so our program now exits without completing.

Is it possible to expose an entry point for an API. Perhaps make [int run(final String... args)](https://github.com/google/closure-templates/blob/master/java/src/com/google/template/soy/AbstractSoyCompiler.java#L162) public?

**Comment by lukesandberg** [comment]
use SoyFileSet.compileToJsSrcFiles or similar

**Comment by tntim96** [comment]
`SoyFileSet.compileToJsSrcFiles` is not public - cant that be changed?

**Comment by lukesandberg** [comment]
Can you not use compileToJsSrc?

**Comment by tntim96** [comment]
I could but it's awkward as it returns a list of strings containing the source, it doesn't write to disk. We have already defined the output path (e.g. `target/template-js/{INPUT_DIRECTORY}{INPUT_FILE_NAME_NO_EXT}.js`) and use it elsewhere via the CLI and would like to re-use this via the API as close to the CLI interface as possible.

**Comment by lukesandberg** [comment]
you could just invoke the compiler via the command line, right?  at worst
you can just fork()

**Comment by tntim96** [comment]
I want to run multiple compilations and then some tests in the same process. Starting a new CLI process is time consuming.

If I fork, the `System.exit` call will still terminate the JVM.

**Comment by lukesandberg** [comment]
sorry, when i said 'fork' i meant 'invoke the compiler as a sub process'

the only api we support that does what you want is the command line api.  you should be able to implement what you want using the SoyfileSetApi (though you will have to do the logic to calculate file names and write files yourself), or you could invoke the compiler as a sub process.  Invoking as a subprocess shouldn't be very much slower than what you were doing before
