### ISSUE TITLE
SoyParseInfoGenerator assumes proto definitions without a java package are in "com.google.protos"

### ISSUE THREAD

**Issue by orischwartz** [google/closure-templates#143]
If a proto file doesn't explicitly declare a java package, parse info generator assumes it's in `com.google.protos`:

[`JavaQualifiedNames.java`](https://github.com/google/closure-templates/blob/6a6a54ff55e1ab6e09dd24703825d5971f450eaa/java/src/com/google/template/soy/types/proto/JavaQualifiedNames.java#L185)

```java
    if (fileOptions.hasJavaPackage()) {
      sb.append(fileOptions.getJavaPackage());
    } else {
      sb.append("com.google.protos");
      if (!file.getPackage().isEmpty()) {
        sb.append('.').append(file.getPackage());
      }
    }
```

I'm guessing this is an internal convention? Any reason why it doesn't follow the protobuf behavior of using the same package as the protobuf package?

**Comment by lukesandberg** [comment]
That is the default behavior at google, I didn't realize it was different
publicly. Thanks for letting me know we should be able to put a fix
together.
