### ISSUE TITLE
Support calling functions in the template

### ISSUE THREAD

**Issue by paladox** [google/closure-templates#144]
Hi could functions be supported in the template please?

Velocity supports this and this part is making it a bit tricky for me to convert a gerrit plugin to use soy (closure template) as you carn't call a function within the template ie something like

{$its.formatLink($changeUrl)}

https://gerrit-review.googlesource.com/#/c/plugins/its-base/+/108215/

**Comment by lukesandberg** [comment]
soy supports calling functions, it just doesn't have a concept of methods.

so you could write something like {formatLink($its, $changeUrl)}

there are a number of builtin functions:
https://developers.google.com/closure/templates/docs/functions

you can also add custom ones, there is some basic documentation here
https://developers.google.com/closure/templates/docs/plugins

**Comment by paladox** [comment]
ah, @lukesandberg hi, how could i do {formatLink($its, $changeUrl)} please?

**Comment by paladox** [comment]
I wonder how i do that in https://gerrit-review.googlesource.com/#/c/plugins/its-base/+/108215/35/src/main/java/com/googlesource/gerrit/plugins/its/base/workflow/action/AddSoyComment.java ?
