### ISSUE TITLE
No tag or release download for 2018-01-03

### ISSUE THREAD

**Issue by tntim96** [google/closure-templates#150]
Hi,

I noticed version [2018-01-03](https://mvnrepository.com/artifact/com.google.template/soy/2018-01-03) was released, but there's no [release download](https://github.com/google/closure-templates/releases) or [git tag](https://github.com/google/closure-templates/tags).

**Comment by emspishak** [comment]
Whoops, sorry about that. We've just added a release/tag: https://github.com/google/closure-templates/releases/tag/release-2018-01-03
