### ISSUE TITLE
Optional parameters not working

### ISSUE THREAD

**Issue by sebastianharko** [google/closure-templates#151]
I have: 
```

{namespace my.namespace}
{template .hello}
{@param? SpaceShip_name: ?}
{@param? SpaceShip_description: ?}
{@param? SpaceShip_mainDestination: ?}
{@param? SpaceShip_destinations: ?}
<section type="alpha">
  <heading>{$SpaceShip_name}</heading>
  <description>{$SpaceShip_description}</description>
</section>
{/template}"
```

This seems to be fairly straightforward. 
However, this template does not work and I get "Param [..] unused in template body." exceptions. I'm using this from Java, btw.  However, I declared all fields to be optional (by using @param?), so I shouldn't see these exceptions.

**Comment by lukesandberg** [comment]
Optional means it is optional for a caller to pass them. You still need to
use all the parameters you declare in the template.
