### ISSUE TITLE
soy.map is undefined which breaks type map<K,V>

### ISSUE THREAD

**Issue by albertsteckermeier** [google/closure-templates#165]
When accessing a map with the @param type map<string,?> I get the following error.
``
Uncaught TypeError: Cannot read property '$$maybeCoerceKeyToString' of undefined
``
The generated line of code looks like this.
``
a.get(soy.map.$$maybeCoerceKeyToString("some-key-of-map")),
``
Looks like soy.map is undefined for some reason.

**Comment by emspishak** [comment]
soy.map.$$maybeCoerceKeyToString is defined in https://github.com/google/closure-templates/blob/master/javascript/soyutils_map.js so you'll need to make sure that file is included in whatever JS build/run setup you have.

**Comment by albertsteckermeier** [comment]
Thanks for the reply. Indeed I forgot to add this file in my build after upgrading the Soy compiler. The ticket can be closed.
