### ISSUE TITLE
Broken docs links

### ISSUE THREAD

**Issue by sgammon** [google/closure-templates#173]
In production, there are some broken links on the Closure Templates main developer site.
If you go to the dev guide, for example, here:
[https://developers.google.com/closure/templates/dev](https://developers.google.com/closure/templates/dev)

And then click on any subpage, you currently get a 404. There are a ton of 404s on this site, and it contains all the useful docs. Can we get some help?

**Comment by teppeis** [comment]
related: https://github.com/google/closure-templates/issues/167

**Comment by iteriani** [comment]
It's not too great right now, but we released some documentation on github. We'll remove the links on developers.google.com soon.
