### ISSUE TITLE
npm does not download the jar files for closure templates!

### ISSUE THREAD

**Issue by kira510** [google/closure-templates#176]
Hello,

I installed the closure templates using, 
_npm install google-closure-templates@latest_

I get this error when i try to build using the closure compiler, 
Missing provide for soy in app/templates/field.soy

So i checked the google-closure-templates folder in node-modules and found that there was no soyutils_usegoog.js like we used to have with old versions.  I just have an index.js file referring to some jar files that were not downloaded. 

Below you can see my index.js file. How can i fix this?

```
module.exports = {
  js: require.resolve('./soy_to_js_src_compiler.jar'),
  incrementaldom: require.resolve('./soy_to_incrementaldom_src_compiler.jar'),
  java: require.resolve('./soy_to_jbc_src_compiler.jar')
};

```

I tried to download this from website but didn't find a good source. The one that i found was https://repo1.maven.org/maven2/com/google/template/soy/2019-03-11/ which does not have jbc-src-compiler.jar . Also i don't feel comfortable with having to downloading exclusively since we have to add it to node-modules folder after installing closure templates in our pipeline. Any help will be great.

Thanks in advance,
Kiran

**Comment by iteriani** [comment]
Sorry I am still learning how to make this work. If you have any ideas how to release jar files to npm, that'd be appreciated.
