### ISSUE TITLE
SoyTofu deprecation notice refers to non-public migration guide

### ISSUE THREAD

**Issue by dpursehouse** [google/closure-templates#177]
The `SoyTofu` class is deprecated and the `@deprecated` tag in its javadoc says:

```
/**
 * @deprecated Use SoySauce instead. Apps/framework users should follow this migration guide
 *     go/af-soy-migration.
 */
```

`go/af-soy-migration` is an internal Google link and is not visible publicly.

Please replace this with a public link, or include the migration guide in this git repository.

**Comment by iteriani** [comment]
It is included in the migration guide. See g3doc -> dev -> soysauce_migration.

**Comment by dpursehouse** [comment]
> See g3doc -> dev -> soysauce_migration

Please provide a link.  As far as I can see there is only a "todo.md" under the g3doc path: https://github.com/google/closure-templates/blob/master/g3doc/todo.md

There is a `http://doc/...` link in there, but it also seems to be a Google internal link.

**Comment by emspishak** [comment]
Here's a link: https://github.com/google/closure-templates/blob/master/documentation/dev/soysauce-migration.md

**Comment by dpursehouse** [comment]
Thanks @emspishak 

Would it be possible to replace the `go/af-soy-migration` in the source code with that link?
