### ISSUE TITLE
Xml external entity injection

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/closure-templates#178]
![图片](https://user-images.githubusercontent.com/39950310/60959130-3e4a5400-a33a-11e9-9178-0f7c7f3281d6.png)
The xml external entity is not disabled when parsing the xml string. When the "xliffContent" is controlled by the attacker, a malicious xml string may be constructed for the xxe attack.

**Comment by lukesandberg** [comment]
We currently expect xliff content to be trusted. Disabling external
entities is probably a good idea but I don’t think this should be
considered an attack vector

**Comment by lukesandberg** [comment]
I landed a fix for this and it should be released with the next push
