### ISSUE TITLE
Feature Request: Support for defining RequireJS/AMD packages

### ISSUE THREAD

**Issue by bregenspan** [google/closure-templates#18]
When Closure Templates was maintained on Google Code, someone submitted a patch to allow building out JS as AMD modules: https://code.google.com/p/closure-templates/issues/detail?id=29 .  This feature would be very useful for us at Gawker Media, so I was wondering whether outside contributions like this are being considered for inclusion now that the project has migrated?

**Comment by Ubehebe** [comment]
@bregenspan [here](https://github.com/google/closure-templates/blob/master/CONTRIBUTING.md) are the directions for contributing. PRs welcome! You'll probably have to prepare the PR yourself, though.

**Comment by bregenspan** [comment]
@Ubehebe many thanks!
