### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by edg84** [google/closure-templates#1832]
src/js/soyutils/soyutils_usegoog.js:46:264 ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "safevalues" never defined.

**Comment by edg84** [comment]
src/js/soyutils/soyutils_usegoog.js:46:264 ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "safevalues" never defined.

**Comment by edg84** [comment]
src/js/soyutils/soyutils_usegoog.js:46:264 ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "safevalues" never defined.

**Comment by edg84** [comment]
https://github.com/google/closure-templates.git

**Comment by emspishak** [comment]
`safevalues` is here: https://github.com/google/safevalues/
