### ISSUE TITLE
Can we get a release?

### ISSUE THREAD

**Issue by sgammon** [google/closure-templates#188]
Sorry to file an issue for this, but it would be sweet if we could get a release cut of Soy.

Upstream, I'm working on integrating `SoySauce`/`SoyTofu` into Micronaut (see micronaut-projects/micronaut-views#13, micronaut-projects/micronaut-views#16). However, the integration needs patches here in Soy, specifically, #185 and #186, which add the `hasTemplate` method.

In any case, those patches are merged, but we don't yet have a release that contains those (it barely missed the `2019-08-22` release), so we have to ship a JAR with Micronaut, which is preventing merge of that change. Thank you in advance for considering my request

**Comment by iteriani** [comment]
Ok I'll release tonight

**Comment by sgammon** [comment]
@iteriani thank you! you guys rock. happy labor day if you're in the US.

**Comment by iteriani** [comment]
I believe I released just now.

**Comment by sgammon** [comment]
@iteriani thank you!
