### ISSUE TITLE
Erroneous String Compare

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/closure-templates#189]
https://github.com/google/closure-templates/blob/f3aa5254595ab0ab66a0aa8e2a4be23b043a3e52/java/src/com/google/template/soy/data/SanitizedContents.java#L273
Strings should be compared with the equals() method, not == or !=.

**Comment by lukesandberg** [comment]
Typically that is true, but in this case we are attempting to ensure that
the user is passing us a constant string, by ensuring that it is interned.
So == is correct in this case.
