### ISSUE TITLE
Build with Bazel

### ISSUE THREAD

**Issue by Yannic** [google/closure-templates#190]
I've created `BUILD` files for building closure-templates with Bazel, and was wondering whether you'd be open to adding them in this repository?

/cc @robfig @sgammon

**Comment by iteriani** [comment]
I can take a look at the PR.

**Comment by Yannic** [comment]
I'll send a PR.

**Comment by robfig** [comment]
Closure Templates is now built with Bazel, so this issue could be closed

**Comment by emspishak** [comment]
Bazel support was added with https://github.com/google/closure-templates/commit/c8f994f15922db35b00c126396b16eab6118bc8f and https://github.com/google/closure-templates/commit/93b855feabed26ef50c6f7fe37021d033f8cb86f and improved with https://github.com/google/closure-templates/commit/f4dd3fb8775133a10508621db3390a55817f8872. Test targets were added in https://github.com/google/closure-templates/commit/5011f192846889e5e06767db299803309cbd5996
