### ISSUE TITLE
Add TypeScript sources for idom runtime

### ISSUE THREAD

**Issue by Yannic** [google/closure-templates#192]
The TypeScript sources got removed in favor of generated closure sources in f6d0b13a00e952bdd6da7dfa27536a436d22e841. Could we get the original TypeScript versions in addition to the closure sources?

**Comment by Yannic** [comment]
Tooling and IDE integration is a lot better for TypeScript. Extracting the sources from source maps isn't fun, and `TypeScript -- tsickle -> closure -- clutz -> .d.ts` isn't that great.

**Comment by iteriani** [comment]
We reverted to closure since we didn't know how users could consume .ts
that relies on clutz. Have you found a way?

**Comment by Yannic** [comment]
I'm working on TypeScript support in a private fork of rules_closure. It works for most of my usecases, but it's far from working for arbitrary workspaces. Hopefully, it'll become good enough to open source it at some point.

**Comment by iteriani** [comment]
OK I'll make sure the next push gets the idom sources

**Comment by iteriani** [comment]
This is done I think...

**Comment by Yannic** [comment]
Thanks a lot!
