### ISSUE TITLE
Support for Type aliases

### ISSUE THREAD

**Issue by necolas** [google/closure-templates#22]
From what I've gathered, there is no easy way to specify type aliases or custom types (especially if you want server- and client-side rendering). We've been using records in our templates, but that leaves us with large amounts of repeated param definitions (that are also responsible for the majority of a template's code). For example:

```
{template .Foo}
  {@param tweet: [
    // massive record
  ]}

  <div>
    {call .Bar}
      {param tweet: $tweet /}
    {/call}
  </div>
{/template}

{template .Bar}
  {@param tweet: [
    // massive record
  ]}

  <div>
    {$tweet.text}
  </div>
{/template}
```

**Comment by lukesandberg** [comment]
I believe the correct way to handle this is to register a new type in the SoyTypeRegistry by implementing a SoyTypeProvider.  I'm not sure if there is documentation for this though.

**Comment by nathancomstock** [comment]
I was looking to do similar today and ended up with an "alias" approach for now. In the tweet example, assuming tweet has `text` and  `public` as members

The provider
```
public class TwitterTypesProvider implements SoyTypeProvider {
  final RecordType tweet = RecordType.of(
    ImmutableMap.<String, SoyType>of(
      "text", StringType.getInstance(),
      "public", BoolType.getInstance()
    ));
  @Override
  public SoyType getType(String typeName, SoyTypeRegistry typeRegistry) {
    return "tweet".equals(typeName) ? tweet : null;
  }
}
```
Then register in a Guice module

```
@Override
protected void configure() {
Multibinder.newSetBinder(binder(), SoyTypeProvider.class).
      addBinding().toInstance(new TwitterTypesProvider());
```

The input

```
{namespace twitter autoescape="strict"}

/**
*
*/
{template .Foo}
  {@param tweet: tweet}
  <div>
    {call .Bar}
      {param tweet: $tweet /}
    {/call}
  </div>
{/template}

/**
*
*/
{template .Bar}
  {@param tweet: tweet}
  <div>
  {$tweet.text}
  </div>
{/template}
```

Produces

```
/**
 * @fileoverview Templates in namespace twitter.
 * @public
 */

if (typeof twitter == 'undefined') { var twitter = {}; }


/**
 * @param {{
 *    tweet: {public: boolean, text: string}
 * }} opt_data
 * @param {(null|undefined)=} opt_ignored
 * @param {Object<string, *>=} opt_ijData
 * @return {!soydata.SanitizedHtml}
 * @suppress {checkTypes}
 */
twitter.Foo = function(opt_data, opt_ignored, opt_ijData) {
  var tweet = goog.asserts.assertObject(opt_data.tweet, "expected parameter 'tweet' of type [public: bool, text: string].");
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div>' + twitter.Bar(opt_data, null, opt_ijData) + '</div>');
};
if (goog.DEBUG) {
  twitter.Foo.soyTemplateName = 'twitter.Foo';
}


/**
 * @param {{
 *    tweet: {public: boolean, text: string}
 * }} opt_data
 * @param {(null|undefined)=} opt_ignored
 * @param {Object<string, *>=} opt_ijData
 * @return {!soydata.SanitizedHtml}
 * @suppress {checkTypes}
 */
twitter.Bar = function(opt_data, opt_ignored, opt_ijData) {
  var tweet = goog.asserts.assertObject(opt_data.tweet, "expected parameter 'tweet' of type [public: bool, text: string].");
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div>' + soy.$$escapeHtml(tweet.text) + '</div>');
};
if (goog.DEBUG) {
  twitter.Bar.soyTemplateName = 'twitter.Bar';
}
```

Tofu type check

```
{call twitter.Foo}
  {param tweet: ['textWrong':'hello twitter', 'public':true] /}
{/call}

//produces
! com.google.template.soy.base.SoySyntaxException:  ...  Argument type mismatch: cannot call template parameter 'tweet' with type '[public: bool, text: string]' with value of type '[public: bool, textWrong: string]'
```
I am going to look at the custom type approach at some point (maybe optional and defaults are possible?), but this seems avoids the repeated param definitions with little effort.

**Comment by lukesandberg** [comment]
fwiw i am more sympathetic to adding language support for this than i once was :)

we could add some basic support for 'typedefs'

{namespace my.project}
{typedef tweet : ['text' : string, 'public': bool] }

then we could let you reference them in other files via the fully qualified name

my.project.tweet

It should be a fairly simple feature to add (with the caveat that our parser is a bit of a mess).

I'm not sure i like the name 'typedef' for this, so consider that a straw man.

**Comment by SLaks** [comment]
I will implement this.

Proposed syntax:

```
{namespace namespace}

{@typedef .SomeType: [text: string, details: root.OtherType]}
{@typedef root.OtherType: string|number}
```

I chose this syntax (in particular, the `@`) to be consistent with `{@param}`.  However, I'm not sure about the `@`.
I'd like to allow typedefs that aren't inside the file namespace, since file namespaces frequently end in `.templates`, and that wouldn't make sense for a type.

I will also change the JS emitter to emit `@record` types (for records, as per #50) or `@typedef`s (for unions & everything else).
For nested records, I'll probably just use `{...}`, not `@record`, since there would be no obvious name.  However, I could generate `@record` types with indexed suffixes for each nested record.

We could also change the Java emitter to emit `@AutoValue` classes for flat record typedefs (this would only work if every field is either a primitive or a different compliant record typedef).  However, I won't implement that (at least, for now).

**Comment by brunobasto** [comment]
@SLaks @lukesandberg Any updates on this?
