### ISSUE TITLE
Guidance requested for JsSrc build setup

### ISSUE THREAD

**Issue by robfig** [google/closure-templates#222]
We use Closure Compiler & Closure Library, and previously Soy templates have "just worked". After upgrading to a more recent Soy compiler, it complains about an unsatisfied dependency on "soy.map", which I do not see in Closure Library or soyutils_usegoog.js from the release. 

I see that it's defined in `//javascript/soyutils_usemap.js` in this repo. Do you recommend that I vendor that, and any other files from that directory that seem to be required, and tweak the build rules to always provide it to the Compiler ? I'm a little uncertain because I see a lot of JS files in that directory and I didn't want to play whack-a-mole. 

Thanks for any advice!

**Comment by iteriani** [comment]
https://github.com/google/closure-templates/blob/master/javascript/soyutils_map.js

should be it.

**Comment by robfig** [comment]
OK, I'll vendor that file. Thanks!
