### ISSUE TITLE
Warning "bootstrap class path not set in conjunction with -source 1.7"

### ISSUE THREAD

**Issue by claudioc** [google/closure-templates#24]
I am fairly new to the library, but I am failing to compile it (trying to add some helpers).

My system is an OSX 10.9 and Java version is "1.8.0_25".

Simply running `ant` will generate the warning which aborts the build process. If I remove the `-Werror` switch in the build.xml file, the compilation finishes without problems.

It's my understanding that SoyToJsSrcCompiler.jar wants Java 1.7 (I had to upgrade my old Java 1.6 to be able to run it), but in the build.xml the target is 1.6 (which is probably what is generating this problem). It seems a bit confusing.

**Comment by claudioc** [comment]
The problems seems to be related to Java 1.8, which outputs that warning thus stopping the compilation process.

The details are here http://www.draconianoverlord.com/2014/04/01/jdk-compatibility.html

**Comment by claudioc** [comment]
Probably duplicated of https://code.google.com/p/closure-templates/issues/detail?id=62

**Comment by claudioc** [comment]
If you can install JDK 1.7, you can compile the library with `JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home ant`

(using the current 1.7, of course)

**Comment by Ubehebe** [comment]
@claudioc The project now has a [pom.xml](https://github.com/google/closure-templates/blob/master/pom.xml), so you should be able to type `mvn package` to build the JAR. The POM also specifies Java 1.7.

**Comment by 8Ozymandias** [comment]
I am getting the same thing in Android Studio. I am trying to set up Google Cloud Endpoints using the instructions provided on the Google Cloud Endpoints repository but when I follow the steps and rebuild the project I always get that error along with a few others.  Could I get some help please?

![image](https://user-images.githubusercontent.com/33201214/33031177-7afb94de-cdeb-11e7-8d36-8cbae46e6454.png)

**Comment by btow** [comment]
Exactly the same problem in Android Studio 3.0.1 (Build #AI-171.4443003, built on November 9, 2017;
JRE: 1.8.0_152-release-915-b01 amd64; JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o; Windows 10 10.0).

`Executing tasks: [clean, :vksdk_library:assembleDebug, :ui:assembleDebug, :app:assembleDebug]

...
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: C:\Users\bobkov-vv\AndroidStudioProjects-Gits\Reestore\core\src\main\java\ru\tinkoff\acquiring\sdk\requests\AcquiringRequest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
..,
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
...
BUILD SUCCESSFUL in 55s
85 actionable tasks: 80 executed, 5 up-to-date
`
