### ISSUE TITLE
SanitizersTest#testNormalizeUriAndFilterNormalizeUri corrupts terminal output

### ISSUE THREAD

**Issue by Ubehebe** [google/closure-templates#27]
If you run `mvn test` from the command line, your terminal will turn into garbage. I believe this is caused by [this line](https://github.com/google/closure-templates/blob/e74fcfa284a1e31d42ac93e53cb84a71f638c70b/java/tests/com/google/template/soy/shared/restricted/SanitizersTest.java#L341) in SanitizersTest:

```
assertEquals("#zSoyz", Sanitizers.filterNormalizeUri("\u000e  javascript:alert('XSS');"));
```

I believe `\u000e` is interpreted by terminals as an ANSI escape code (specifically ["change screen to 16-color graphics"](http://ascii-table.com/ansi-escape-sequences.php)). This input makes it to the console because Sanitizers#filterNormalizeUri [logs the malformed input directly to a java.util.logging.Logger](https://github.com/google/closure-templates/blob/5f3b28dc75800e5ab6c145357ce05368298a73e6/java/src/com/google/template/soy/shared/restricted/Sanitizers.java#L410).

This is more of an annoyance than a problem; the corrupted terminal doesn't cause the tests to fail, and you can get back to a good state by typing `reset`. (It also doesn't affect Google internally.) But it would be nice to fix before we create a CI server for the project.

I'm against adding logic to Closure Templates to escape strings for terminal display, or adding a dependency on a library that has such logic. I think the easiest thing to do is just configure the tests to log at level `SEVERE` (since the corrupting log message is a `WARNING`). @tbroyer, @nathancomstock, WDYT?

**Comment by tbroyer** [comment]
SGTM.

I don't have any experience with this kind of setup but found http://bpossolo.blogspot.fr/2013/04/configuring-javautillogging-for-unit.html

**Comment by lukesandberg** [comment]
in that exact test you should be able to just call
java.util.Logger.getLogger(Sanitizers.class.getName()).setLevel(SEVERE)
which would fix the problem

**Comment by nathancomstock** [comment]
I've not seen the issue, but validated fix proposed from @tbroyer which works well.
