### ISSUE TITLE
commonJS asynchronous module definition support

### ISSUE THREAD

**Issue by mkaatman** [google/closure-templates#31]
Migrated from https://code.google.com/p/closure-templates/issues/detail?id=29

Jamon has moved on to using React, but others might still find his patch useful.
https://code.google.com/p/closure-templates/issues/attachmentText?id=29&aid=-6428444581076525520&name=useCommonJsAsyncDef.patch&token=ABZ6GAeKnA2uHc77T5Pca4kZNcsDviSeug%3A1424996967565

--useCommonJsAsyncDef
          usage = "When this option is used, each generated JS file with be wrapped with define() command and will specify external callees as dependencies according to the CommonJS asynchronous definition proposal.  Use in conjunction with --dependencies"

**Comment by Ubehebe** [comment]
We need someone to take this patch into a PR so we can do a code review. Volunteers?

**Comment by iteriani** [comment]
It's likely that we'll move to using ES6 modules or TypeScript rather than commonjs.
