### ISSUE TITLE
Undefined method when compiling soyutils_usegoog.js

### ISSUE THREAD

**Issue by ernestoalejo** [google/closure-templates#38]
When I try to compile the file with the rest of scripts of my application the compiler outputs this error:

```
client/vendor/closure-templates/soyutils_usegoog.js:1864: ERROR - Property runtimeType never defined on goog.debug
      (goog.DEBUG ? (', but got ' + goog.debug.runtimeType(param)) : '') +
```

I am using `goog.DEBUG=false` in the compiler flags. I've tried to find the method in the Closure Library but I don't know where it's defined or why it's not found.

**Comment by concavelenz** [comment]
https://github.com/google/closure-library/blob/f4b6ae81da22129befdcb35a0681c60bcca0451d/closure/goog/debug/debug.js#L628

**Comment by ernestoalejo** [comment]
My fault, I was using a cached version of the library from an internal repo. Thank you for the help!

**Comment by concavelenz** [comment]
No problem
