### ISSUE TITLE
Publish latest release to maven repository

### ISSUE THREAD

**Issue by matiwinnetou** [google/closure-templates#4]
I am not sure, who has permissions to publish to maven repository for com.google.template but it would be nice to see latest released published there. I could help with that but I lack permissions.

http://mvnrepository.com/artifact/com.google.template/soy

**Comment by matiwinnetou** [comment]
I actually don't think google has any desire to release to maven central, this task has to be carried out by a community member.

**Comment by Ubehebe** [comment]
@matiwinnetou @tbroyer After moving some source code around internally, we're now able to accept PRs ([directions](https://github.com/google/closure-templates/blob/master/CONTRIBUTING.md)). Would either of you like to write a pom.xml?

**Comment by tbroyer** [comment]
@Ubehebe Sure I'll have a look. Is all you need a pom.xml? or would you also like to have scripts or whatever to ease deployments to Central? (I believe I had started working on it already a while ago)

**Comment by Ubehebe** [comment]
@tbroyer pom.xml would be a good start. Once we have that, we should be able to release to Central with just a `mvn deploy`.

**Comment by tbroyer** [comment]
@Ubehebe Do you mean replacing Ant with Maven as the build tool for the project? Or using [`mvn deploy:deploy-file`](https://maven.apache.org/plugins/maven-deploy-plugin/deploy-file-mojo.html) with a `pom.xml` file, and the JARs created by the Ant build? (FWIW, we do the later for GWT, still using Ant for now to build the project, and a shell script to deploy to a Maven repository)

**Comment by Ubehebe** [comment]
@tbroyer I'd totally be open to replacing Ant with Maven. My understanding (correct me if I'm wrong) is that Maven is the standard build tool in open-source Java these days. If we host on Maven Central, anyone who still needs to use Ant can just download the JARs manually and keep them.

Switching to Maven would also let us get rid of versioned JARs we currently have in source control, which would be nice.

WDYT? Should we check on closure-templates-discuss to see if anyone cares about Ant?

**Comment by tbroyer** [comment]
@Ubehebe At least one person asked for a Maven build: https://groups.google.com/forum/#!topic/closure-templates-discuss/B2gHKT0vzAw

But yes maybe there should be some discussion/poll before changing the build tool. Let's move this discussion to the group (I'll let you open the thread if you don't mind)

I'll work on a script to deploy the Ant build output to a Maven repo (similar to what we do for GWT currently), and then maybe move to Maven as a replacement for Ant.

**Comment by Ubehebe** [comment]
@tbroyer [Done](https://groups.google.com/d/msg/closure-templates-discuss/B7eQtudvx94/wWjlP5H1inAJ).

**Comment by mwhipple** [comment]
I have a fork that uses gradle to integrate with the existing ant file, generate a pom, and presently publish to bintray/jcenter (which could then be synchronized to maven central or I could add direct support for maven central). It may need some tuning (but the major pieces should be done).  I can submit a pull request if desired.

**Comment by Ubehebe** [comment]
@mwhipple I'd prefer to get rid of the Ant stuff first and delete our vendored JARs. Gradle has pretty good interop with Maven, right?

**Comment by mwhipple** [comment]
@Ubehebe It depends on what you mean by interop.  Gradle has great support for working with Maven repositories but is mostly a replacement for the build tool itself. It does have some support for interoperatbility with the maven tool but I think maven is a little too opinionated to play overly well with others. Gradle by default has the same convention over configuration approach and dependency management capability but is less restrictive. It does have very strong (bi-directional) Ant integration so the existing build system could be migrated smoothly if that makes more sense than a wholesale uprooting of the current build process. I added a quick rundown next to the build file in the branch: https://github.com/mwhipple/closure-templates/blob/mw/GRADLE.md. I'm also tidying up some of the integration points now so I can generate sources jars, etc.

**Comment by tbroyer** [comment]
@Ubehebe @mwhipple Building Closure Templates with Maven is (relatively) easy; generating the same JARs will require a bit more work. Running examples would be harder, but is this really needed?

**Comment by mwhipple** [comment]
@tbroyer By "this" you mean running examples? (not that I have an answer).

I should be able to take on porting to Gradle if there's interest/comfort in that option. All of the existing build logic could be handled without issue.

**Comment by nathancomstock** [comment]
I have a [maven config](https://github.com/nathancomstock/closure-templates/blob/master/pom.xml) and [deployment](https://github.com/nathancomstock/maven-repo/tree/master/releases/nathancomstock/github/closure-templates/2015-01-16) of maven build. The examples are run using exec plugin. Last I checked the maven build covered everything provided in the ant tasks, but I need to review since latest commits. I personally do not have maven/gradle preference, but would be happy to update/review my existing maven build and submit PR if desired.

**Comment by Ubehebe** [comment]
@nathancomstock The `pom.xml` looks pretty good. Sure, send a PR.

**Comment by tbroyer** [comment]
@nathancomstock Looks good!

I notice you run one example during the verify phase; running examples from the CLI wouldn't be as easy as a with Ant though.

**Comment by nathancomstock** [comment]
@tbroyer Good point. I will look into cli options for examples.

**Comment by nathancomstock** [comment]
@Ubehebe, 
Opened #23 for this issue. 

@tbroyer , 
I did not see great options for running examples as easily as with ant. I looked at an option using the [appassembler-maven-plugin](http://mojo.codehaus.org/appassembler/appassembler-maven-plugin/usage-program-scripts.html) which worked, but bloated the pom. In the current state of the PR, `mvn verify -DskipTests=true -Dmaven.javadoc.skip=true` can be used to run the examples.

**Comment by tbroyer** [comment]
@nathancomstock Yes, this is why I questioned above whether running the samples (individually, from the CLI) was really needed (they should of course be run during the build as a verification check). I for one am fine with what you did in your PR.

**Comment by Ubehebe** [comment]
@nathancomstock @tbroyer I'd like to push to Maven Central soon. I'm used to using the nexus-maven-staging-plugin to do this via `mvn deploy`, but the POM doesn't have this plugin. Is there a better way to do this?

**Comment by tbroyer** [comment]
I never used that plugin. I just `mvn deploy` for snapshots, and `mvn release:prepare` and `mvn release:perform` for releases, followed by manually closing and releasing the staging repo at oss.sonatype.org

**Comment by nathancomstock** [comment]
@Ubehebe , I also have not used the plugin. If you would like me to add the plugin let me know, just cant test it of course...

**Comment by Ubehebe** [comment]
@nathancomstock @tbroyer Okay, I've [pushed fresh artifacts to Maven Central](https://groups.google.com/d/msg/closure-templates-discuss/xmXJjPGRc_w/WXIFSmtuDQsJ). I had to add a few plugins and things to the POM. Can one of you grab the Maven JARs and make sure nothing is broken? Once you do, I'll send you a PR with my POM additions.

**Comment by jamestyrrell** [comment]
@Ubehebe A million times thank you!

**Comment by nathancomstock** [comment]
@Ubehebe , missed the previous issue update notification somehow...the 02-10 jars are working for me.

**Comment by ChadKillingsworth** [comment]
@Ubehebe Can you tag the release commits? I'm really only interested in the latest one (4-3-2015).
