### ISSUE TITLE
documentation bug: busted github link in index of Closure Templates Google Develoers site

### ISSUE THREAD

**Issue by jmhodges** [google/closure-templates#45]
Couldn't find the actual code for [the Google Developers Closure Templates](https://developers.google.com/closure/templates/index#how-do-i-start) page in here for the closure-templates-docs repository.

But there is a busted "project's source code" link in that "How Do I Start" section. It points to "https://github/google/closure-templates/" instead of "https://github.com/google/closure-templates/"

(Also, where is the repo for that page? It says its Apache licensed but it's definitely not in the closure-templates-docs repo.)

**Comment by iteriani** [comment]
We've moved the docs to github.
