### ISSUE TITLE
Export JS @typedef for template parameters

### ISSUE THREAD

**Issue by oujesky** [google/closure-templates#50]
Consider the following template built with `--shouldGenerateJsdoc` parameter with strict typing:

```
{namespace test}
{template .template}
    {@param stringParam: string}
    {@param htmlParam: html}
    {@param listParam: list<string>}
    ...
{/template}
```

The generated JS code looks pretty much like this:

``` javascript
/**
 * @param {{
 *    stringParam: string,
 *    htmlParam: (soydata.SanitizedHtml|string),
 *    listParam: !Array<string>
 *    ...
 * }} opt_data
 * @param {(null|undefined)=} opt_ignored
 * @return {!soydata.SanitizedHtml}
 * @suppress {checkTypes}
 */
test.template = function(opt_data, opt_ignored) {
  ...
};
```

When you need to pass the `opt_data` to `goog.soy.renderXx()` method for example from return value of an another method, you have to copy paste quite considerable type definition, if you want Closure Compiler to pass without errors on such code. The more parameters, the more copy pasting needed of course.

``` javascript
/**
 * @return {{
 *    stringParam: string,
 *    htmlParam: (soydata.SanitizedHtml|string),
 *    listParam: !Array<string>
 *    ...
 * }}
 */
test.getOptData = function() {
    return { ... }
}

test.render = function() {
    goog.soy.renderElement(test.template, this.getOptData());
    ...
```

It would be much easier to have generated `@typedef` available for usage in these cases, for simplification like this:

``` javascript
/**
 * @return {test.template.TypeDef}
 */
test.getOptData = function() { ...
```

The generated template code might look following:

``` javascript
/**
 * @param {test.template.TypeDef} opt_data
 * @param {(null|undefined)=} opt_ignored
 * @return {!soydata.SanitizedHtml}
 * @suppress {checkTypes}
 */
test.template = function(opt_data, opt_ignored) {
  ...
};

/**
 * @typedef {{
 *    stringParam: string,
 *    htmlParam: (soydata.SanitizedHtml|string),
 *    listParam: !Array<string>
 *    ...
 * }};
 */
test.template.TypeDef;
```

I had a short sweep through the code involved and I can come with PR if this is considered useful and acceptable. I guess some command line switch for this behaviour would be appropriate.

**Comment by SLaks** [comment]
I will implement this.

It will generated 
```js
goog.provide('namespace.template.Parameters');

...

/** @record @struct */
namespace.template.Parameters = function() {};

/** @type {number} */
namespace.template.Parameters.prototype.paramName;

...
```

**Comment by SLaks** [comment]
Question:

If a template calls another template with `data="all"`, should the `Parameters` for the caller duplicate all of the parameters of the callee, or `@extend` the callee's `Parameters` (potentially plural)?

**Comment by SLaks** [comment]
Answer to my question: It can't extend the other record, since the duplicated parameters are all optional.

**Comment by iteriani** [comment]
I think this got fixed.
