### ISSUE TITLE
Upgrade to Guice 4.0

### ISSUE THREAD

**Issue by ClaireNeveu** [google/closure-templates#56]
Closure templates cannot be used alongside other projects that use Google Guice and have upgraded to 4.0 due to breaking changes in the library. It would be nice if Closure Templates could release a new version compile against Guice 4.0.

**Comment by lukesandberg** [comment]
Thanks.  We actually use guice 4.0 (well guice head really) internally. So this should just be a matter of updating our pom.  Care to send a PR?

**Comment by hamaron** [comment]
@lukesandberg Would you mind if I sent a pull request for this? I'm really having trouble with this issue.

**Comment by hamaron** [comment]
Created a PR for this: #73

**Comment by hamaron** [comment]
@lukesandberg Bump. Could this change be pulled into the next release?

**Comment by iteriani** [comment]
This has been released.
