### ISSUE TITLE
Consider create new release from closure-templates@HEAD

### ISSUE THREAD

**Issue by davido** [google/closure-templates#577]
Can you please consider to cut a new release?

GerritCodeReview project was trying to update `guava` dependency to `31.0.1-jre`.

As the consequence, `closure-templates` has to be bumped to `closure-templates@HEAD`.

Temporarily, I conducted this release and published it to my GH fork of `closure-templates`: [1].

It would be great to have a regular release, so that we could consume new version of `closure-templates` from Maven Central and not depend on intermediate custom releases. Not to mention, that GH has sometimes outages and is not very reliable.

More context in this upstream issue: [2] and this CL: [3].

//CC @hanwen @edwinkempin @jrn

[1] https://github.com/davido/closure-templates/releases/tag/2022-01-18
[2] https://crbug.com/gerrit/15574
[3] https://gerrit-review.googlesource.com/c/gerrit/+/328339

**Comment by emspishak** [comment]
This is done now.

https://github.com/google/closure-templates/commit/cf8e2908c532e4bec87256b78e5682ae032e0f5d is a pretty big change in that it no longer allows `.` before template names. So we released https://github.com/google/closure-templates/releases/tag/release-2022-03-02 right before that commit (which is the most up-to-date release that still allows `.` template names) and https://github.com/google/closure-templates/releases/tag/release-2022-03-07 including that commit (and more).
