### ISSUE TITLE
How can live without inheritance in closure templates in big project?

### ISSUE THREAD

**Issue by itsacat** [google/closure-templates#58]
We use closure library and closure compiler, and we want to use closure templates.
But closure templates haven't got inheritance. That's really a problem for us.

As I understand, the reason why closure templates don’t have inheritance, is because templates must be simple, and easy to read.

But how can you live without inheritance in big projects?

For example, we have a template file *button.soy* that generates button with public template `project.createButton` and private templates: `project.createOpenTag_`, `project.createCSSClasses_`, `project.createAttributes_`, `project.createContent_`, `project.createCloseTag_`.
We have js class `project.Button`, and we have `project.ButtonCircle` (perhaps this separate class `project.ButtonCircle` seems unnecessary, but it's just an example) which extends `project.Button`.
`project.ButtonCircle` needs little changes made in `project.createButton` template.

Of course we can add new functionality to `project.createButton`, but it's a very bad idea, because such approach will create monster templates in the future.

Or we can create public template `project.createCircleButton` in file *button-circle.soy*, call all private templates from `project.createButton` in it, and when we need to 'override' one of these private templates, (for example `project.createCSSClasses_`), we just create new private template in *button-circle.soy* with name `project.createCSSClassesCirbleButton_`.
Yet in this case we need to copy-paste all content from `project.createButton` to `project.createCircleButton`. That's terrible.

Also we tried using Delegate Templates, but it's not suited for inheritance.

What is approach towards this problem?

I also post this question here: http://stackoverflow.com/questions/32737422/how-can-live-without-inheritance-in-closure-templates-in-big-project

**Comment by concavelenz** [comment]
Check out delegate templates:
https://developers.google.com/closure/templates/docs/commands?hl=en

**Comment by ntstv** [comment]
@concavelenz, Delegates templates doesn't intended to be used multiple times.

_button.soy_
```
{namespace button.Template}

{template .base}
//...
{delcall button.Template.foo /}

{/template}

{deltemplate button.Template.foo }
    //....
{/deltemplate}
```

_button-cricle.soy_
```
{delpackage buttonCircle.Template}
{namespace buttonCircle.Template}

{template .base}
//...
{delcall button.Template.foo /}

{/template}

{deltemplate button.Template.foo }
    //....
{/deltemplate}
```

For example if _buttons-circle.soy_ overrides some `deltemplate button.Template.foo` from _button.soy_ it should contain something like `delpackage buttonCircle.Template`.

So if we want use `.base` from _button.soy_ and _button-circle.soy_ we should provide `delpackge`. In Java we clearly set which _delpackage_ we want. But in JS, google closure compiler automatically choose _delpackage_, base on `goog.require`. And calling `button.Template.foo` from _button.soy_ will actually call `button.Template.foo` from _button-circle.soy_ !

That means we can use only one kind of `button.Template.foo` in whole application! And we can't organize inheritance based on `deltemplate`

Similar there https://groups.google.com/forum/#!topic/closure-templates-discuss/CTGBEn74iBE

**Comment by lukesandberg** [comment]
use composition instead of inheritence?

project.createButton could provide ways for callers to modify its behavior
via parameters, then you could write templates to specialize these core
templates by passing certain parameters.

**Comment by itsacat** [comment]
As i say, that approach will create monster templates, with many ```if```.

**Comment by lukesandberg** [comment]
not necessarily.  instead of behavior switches just pass content

{template .baseButton}
  {@param? attrs : attributes}
  {@param content: string}
  <div class="baseButton" {$attrs ?: ''}>{$content}</div>
{/template}

that would allow for users to pass custom attributes optionally, thus
specializing the implementation.

So instead of trying to 'override a template' just pass information into
the template and have different callers pass different values

**Comment by lukesandberg** [comment]
I believe this is all working as intended.  Large projects using soy (and other programming languages like cc and go) get by without inheritance.
