### ISSUE TITLE
new Maven artifacts please

### ISSUE THREAD

**Issue by pandacalculus** [google/closure-templates#62]
Hi folks,

The current artifacts on Maven central are old; `2015-04-10` and `2.5.0-SNAPSHOT`. It would be great to get new versions published, because `2015-04-10` has some problems that are already fixed on master.

My preference would be for a named release, because I'd prefer not to depend on a SNAPSHOT version in production

Thanks,
-Brendan

**Comment by pandacalculus** [comment]
any update on this?

**Comment by lukesandberg** [comment]
There has been some trepidation about releasing new official versioned releasea since we do not current posses any processes for doing so.  

I think we still need to come up with
Release notes
Compatibility guarantees
Migration instructions
And presumably other things as well....

**Comment by concavelenz** [comment]
Those are nice to have but can be back filled as time goes on.  The Closure
Compiler release every ~6 weeks with minimal formality with versions like
20151118.00

**Comment by lukesandberg** [comment]
We are moving to a monthly release cycle. The first release under the new
regime should land in early January.

**Comment by pandacalculus** [comment]
@lukesandberg that's great to hear! thanks for the update.

**Comment by fantayeneh** [comment]
Hi @lukesandberg,  Is the release is still scheduled for early January?

**Comment by iteriani** [comment]
We just released a new version. I'll try to keep it updated weekly.
