### ISSUE TITLE
TemplateBasicNode (probably SoyNode)  toSourceString prints let statements incorrectly

### ISSUE THREAD

**Issue by lennel** [google/closure-templates#66]
given this template let statement inside a template
 {let $BaseTimestamp : subtract($FromTimestamp, modulo($FromTimestamp, (1000 \* 60 \* 60 \* 24))) /}
when extracting the source from a template in a custom visitor pass with toSourceString, the let statement is rewritten as 
{let $BaseTimestamp : subtract($FromTimestamp, modulo($FromTimestamp, (1000 \* 60 \* 60 \* 24)))}
which does not compile properly.

**Comment by lukesandberg** [comment]
toSourceString is really a debugging feature (we have actually discussed
removing it...)... it isn't a great tool for code generation because it
doesn't preserve whitespace.  A better approach is probably to use the
SourceLocation to extract the original text

**Comment by lennel** [comment]
if I fix it will you publish it, damn sight easier than cutting lines from a text file.

**Comment by lukesandberg** [comment]
yep, send a PR

**Comment by StefanLiebenberg** [comment]
https://github.com/google/closure-templates/pull/93
