### ISSUE TITLE
What is alternative for deprecated-noautoescape?

### ISSUE THREAD

**Issue by FedorGuryanov** [google/closure-templates#77]
Is there any way to directly insert an html to template, working with soy templates 2016-01-12 version?

In old versions (2012-12-21 for example) we were able to use autoescape="false".
In newer versions (to 2015-04-10) we were able to use autoescape="deprecated-noautoescape".

In 2016-01-12 this deprecated API was removed, and I can't find alternative for deprecated-noautoescape (I was looking for it there https://developers.google.com/closure/templates/docs/security)

**Comment by lukesandberg** [comment]
where is the html coming from?

**Comment by FedorGuryanov** [comment]
Html coming from trusted source (rendering dynamically)

**Comment by concavelenz** [comment]
In Java or JavaScript?

**Comment by FedorGuryanov** [comment]
In Java

**Comment by lukesandberg** [comment]
Then you can pass it using one of the helpers in
com.google.template.soy.data to construct a SanitizedContent object with
ContentKind.HTML  SanitizedContents or UnsafeSanitizedContentOrdainer.
