### ISSUE TITLE
|truncate directive acts on escaped content, but should act on pre-escaped content

### ISSUE THREAD

**Issue by hitsthings** [google/closure-templates#8]
`{'12"45"'|truncate:6}` is printed as `12&...` because it acts on the expanded HTMl entities like `&quot;`
`{'12"45"'|truncate:6|escapeHtml}` forces ordering and is printed as `12"45"` (the HTML source is `12&quot;45&quot;`)

I can't see the usefulness of acting on the escaped HTML and it causes artifacts (like ampersands) to appear in your output HTML, so the latter behavior seems more sane by default.

**Comment by Ubehebe** [comment]
This does seem like surprising behavior. If you can change it and keep all the existing tests passing, send a PR.
