### ISSUE TITLE
Closure Templates can't run on App Engine

### ISSUE THREAD

**Issue by jart** [google/closure-templates#80]
The source/runtime version was set to Java 8 in the following commit: https://github.com/google/closure-templates/commit/db3c060fc26c85805da178a80908db4097576a39

This makes it impossible to deploy anything that links against soy to App Engine, or anything where the runtime environment is Java 7.

**Comment by jart** [comment]
@Ubehebe This issue seems to be causing a lot of problems. Could you please take a look at this issue?

**Comment by iteriani** [comment]
iirc, app engine works with java 8 now?
