### ISSUE TITLE
SoyToIncrementalDomSrcCompiler.jar build target

### ISSUE THREAD

**Issue by hochhaus** [google/closure-templates#85]
The idom backend code appears to have all been open sourced. However, no SoyToIncrementalDomSrcCompiler.jar is included in the open source project. This means building a custom compiler is currently required to use idom.

**Comment by sparhami** [comment]
Looks like this just needs to be synced over to Github. In the mean time, you can use the version on NPM which I'll try to update somewhat often:

https://www.npmjs.com/package/closure-templates-incrementaldom
