### ISSUE TITLE
SoyToIncrementalDomSrcCompiler issue when calling template inside if command

### ISSUE THREAD

**Issue by mairatma** [google/closure-templates#91]
If you call a template directly inside an `if` command, the compiled file uses the ternary operator but forgets to add a line break before the next statement, causing syntax errors. For example:

```
{namespace If}

/**
 * @param flag
 */
{template .render}
  {if $flag}
    {call .content /}
  {/if}
  Bar
{/template}

/**
 */
{template .content}
  Foo
{/template}
```

The compiled soy:
```js
function $render(opt_data, opt_ignored, opt_ijData) {
  (opt_data.flag) ? $content(null, null, opt_ijData) : ''  itext('Bar');
}
```

**Comment by sparhami** [comment]
I don't think this has been synced yet to the opensource repo, but I updated closure-templates-incrementaldom on npm with a fix.

**Comment by eduardolundgren** [comment]
Thanks @sparhami, we will test it.

**Comment by mairatma** [comment]
Btw, we've checked and this has indeed been fixed for the `closure-templates-incrementaldom` npm package.
