### ISSUE TITLE
SoyToIncrementalDomSrcCompiler issue with html|string param

### ISSUE THREAD

**Issue by mairatma** [google/closure-templates#96]
If a param's type is defined as `html|string` it will always be rendered as a string, so passing html will try to render a function instead. For example:

```
{template .render}
  {@param content: html|string}
  {$content}
{/template}
```

This soy is compiled to:

```js
function $render(opt_data, opt_ignored, opt_ijData) {
  soy.asserts.assertType((opt_data.content instanceof Function) || (opt_data.content instanceof goog.soy.data.SanitizedContent) || (opt_data.content instanceof soydata.UnsanitizedText) || goog.isString(opt_data.content), 'content', opt_data.content, '!soydata.SanitizedHtml|string');
  var content = /** @type {!soydata.SanitizedHtml|string} */ (opt_data.content);
  itext((goog.asserts.assert((content) != null), content));
}
```

**Comment by mairatma** [comment]
Hey, does anyone have an update on this? It's been great being able to use soy compiled to incremental dom, but this kind of use case (which is very common) is just not possible anymore :(

**Comment by sparhami** [comment]
Looks like support for this should be in the Github version now.

**Comment by mairatma** [comment]
Do you know if this fix also covers https://github.com/google/closure-templates/issues/90? It's a very similar one.

Also, like I mentioned in https://github.com/google/closure-templates/issues/92, would it be possible to publish a new version of the [npm package](https://github.com/google/closure-templates/issues/92) with this?

**Comment by mairatma** [comment]
Hey @sparhami, could you publish a new version of the npm package with this and other fixes? We're really struggling to use incremental dom without this :(

**Comment by sparhami** [comment]
Sorry, haven't had a chance to do so yet. Working on it. Long term, I think Github will be the place for the latest version.

**Comment by mairatma** [comment]
Could you explain how I would use the version here in github? Would I need to build the jar myself? If so, which steps would I need to follow? If I can at least build it I could add it directly in my project for now, instead of getting from npm.

**Comment by mashedcode** [comment]
@mairatma you can simply build and test everything with `mvn install`.

The jar files will be then located in the `target/` folder.

**Comment by hochhaus** [comment]
Also, jars are available on maven.org

http://repo1.maven.org/maven2/com/google/template/soy/2016-08-25/soy-2016-08-25-SoyToIncrementalDomSrcCompiler.jar

**Comment by mairatma** [comment]
Thanks a lot! Will try.
