### ISSUE TITLE
Feature request: Providing tar.gz download url

### ISSUE THREAD

**Issue by MarkusBordihn** [google/closure-templates#98]
At the moment the closure template compiler is only available as "zip" file:
https://dl.google.com/closure-templates/closure-templates-for-javascript-latest.zip

For compatibility reasons it would be great to have an "tar.gz" version as well:
https://dl.google.com/closure-templates/closure-templates-for-javascript-latest.tar.gz

**Comment by mikesamuel** [comment]
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.template%22%20AND%20a%3A%22soy%22 has download links for all the published artifacts and those are properly signed as well.

**Comment by MarkusBordihn** [comment]
My use case is an build framework / script which is automatically fetching the latest version.

If I want to use maven for this I need to build something for the maven api to find and fetch the latest version. (Which I want to avoid, if possible)
