### ISSUE TITLE
Closure Templates Protobuf support

### ISSUE THREAD

**Issue by jart** [google/closure-templates#99]
Google has excellent internal support for using protobufs in Soy templates. But it's not available in the open source world. @lukesandberg [said](https://groups.google.com/forum/#!topic/closure-templates-discuss/PAXx6SKMm5Y) this feature is planned, but no one is currently working on it.

What would it take to expedite this process @Ubehebe? Would @thomasvl and @xfxyjwf who are working on open source proto3 be able to help? Is there anything I can do?

I ask because I'm working on [Closure Rules](https://github.com/bazelbuild/rules_closure) which is in some respects blocked by this issue. The goal of Closure Rules is to make Google's web development methodology freely available to everyone. Closure Templates and Protocol Buffers are an integral part of that vision. But right now they only work together for Googlers. So the open source community is at a disadvantage, because they can't write Closure Templates the same way Googlers do.

I've also spoken with people from two separate companies who've come to me expressing a need for this functionality. Both @hochhaus (SameGoal Inc.) and @wolfgangmeyers (Donuts Incorporated) really want to be able to use Closure Templates to their full potential. They've had to invest a lot of time and energy into finding viable workarounds. My team at Google also encountered similar pains due to this issue.

We would all be very grateful if the Closure Templates team would consider making this issue a priority.

**Comment by mikesamuel** [comment]
https://github.com/google/closure-templates/commit/92286d921b69339807e1de90235364d82b2f6997 open-sources a lot of previously google-only code related to protocol buffers.

**Comment by jart** [comment]
I'll start integrating this into a Closure Rules branch over the next week, in addition to writing tests and migrating my team's service. If there are any remaining issues, I should hopefully be able to spot them. Then I imagine once new releases are cut, we can start bringing this exciting news to the Closure community.

CC: @hochhaus @wolfgangmeyers

**Comment by hochhaus** [comment]
Thanks @mikesamuel!

I see that SoyToJsSrcCompiler.jar now has a --protoFileDescriptors flag. However, SoyToIncrementalDomSrcCompiler.jar does not have a similar flag.

Are protobufs supported in idom templates? If so, code that code be open sourced as well?

**Comment by jart** [comment]
@lukesandberg might be a good person to answer @hochhaus' question regarding SoyToIncrementalDomSrcCompiler supporting protocol buffers.

**Comment by hochhaus** [comment]
@mikesamuel I looked into using SoyToJsSrcCompiler.jar with --protoFileDescriptors but the variable for that flag appears to not be read. Is it possible some required glue is missing in the open source repo?

```
ahochhaus@ahochhaus-pc:~/closure-templates$ grep -ri protoFileDescriptors .
./java/src/com/google/template/soy/SoyParseInfoGenerator.java:  @Option(name = "--protoFileDescriptors",
./java/src/com/google/template/soy/SoyParseInfoGenerator.java:  private static final List<String> protoFileDescriptors = new ArrayList<>();
./java/src/com/google/template/soy/SoyToJsSrcCompiler.java:  @Option(name = "--protoFileDescriptors",
./java/src/com/google/template/soy/SoyToJsSrcCompiler.java:  private static final List<String> protoFileDescriptors = new ArrayList<>();
ahochhaus@ahochhaus-pc:~/closure-templates$ 
```

**Comment by jart** [comment]
Yes it actually turns out we forgot to ask moe to open source one important
chunk of code, off in a main function. We'll get that out soon. Thanks for
taking the time to help us test this!

**Comment by lukesandberg** [comment]
SoyToIncrementalDomSrcCompiler should support protos just as well as
SoyToJsSrcCompiler.  Sorry I haven't been following the opensource efforts
to closely but my guess is that it is just missing a tiny bit of glue code

**Comment by mikesamuel** [comment]
@hochhaus Yeah.  I've got a change pending to add the flags.  I'll push that soon.  Sorry for the delay.

**Comment by hochhaus** [comment]
Awesome. I see the `--protoFileDescriptors` flag has landed for both soy compilers. I'll be playing with this new functionality tonight!

@mikesamuel Thanks for all of the work it took to get this released.

**Comment by jart** [comment]
Now that the missing functionality is in, are we ready to do another Maven push @mikesamuel?

Also, I took the trouble of writing [release notes](https://github.com/bazelbuild/rules_closure/releases/tag/0.2.5) for the Soy release you cut last week. I spent a lot of time scrolling through commits to do that as best as I could. You might want to copy/paste what I wrote and use it for the release notes on this project.

**Comment by mikesamuel** [comment]
Yes Andy.  Thanks for doing the remotes, Justine.  I'll push to central

**Comment by mikesamuel** [comment]
Sorry for the delay.  `<version>2016-08-09</version>` contains support in the jbcsrc, jssrc, and tofu backends.

- http://search.maven.org/#artifactdetails%7Ccom.google.template%7Csoy%7C2016-08-09%7Cjar

The jssrc backend requires the jspb namespace which is provided at https://github.com/google/protobuf/tree/master/js/message.js and the debug.js and map.js files.

**Comment by mikesamuel** [comment]
That last push was missing some JavaScript library code needed by the jssrc backend.

https://github.com/google/closure-templates/blob/master/pom.xml#L820-L826 specifies a new JAR which bundles all the supporting JS files.

**Comment by hochhaus** [comment]
Thanks for adding the jssrc jar. I am still seeing some missing namespaces though. Could you point me at the open source code that provides the following namespaces?

```
proto.webutil.html.types.SafeHtmlProto
proto.webutil.html.types.SafeScriptProto
proto.webutil.html.types.SafeStyleProto
proto.webutil.html.types.SafeStyleSheetProto
proto.webutil.html.types.SafeUrlProto
proto.webutil.html.types.TrustedResourceUrlProto
```

**Comment by mikesamuel** [comment]
You have to compile html.proto to js.  I can attach the js once I've got more than a mobile device available but you can get the .proto file from github.com/google/safe-html-types.

**Comment by hochhaus** [comment]
Thanks Mike. No need to attach the js, now that I know where it is located I can generate it.

**Comment by jart** [comment]
This issue appears to be resolved. It's now being integrated into the Closure Rules build system! https://github.com/bazelbuild/rules_closure/pull/124
